package com.ebay.park.util;

import org.apache.commons.lang.RandomStringUtils;

import java.util.Arrays;

/**
 * It contains the password varieties.
 * @author Julieta Salvadó
 */
public class Password {
    private String simplePassword;
    private byte[] hashedPassword;

    public Password() {
        this.simplePassword = getAutogeneratedPassword();
        this.hashedPassword = getHash(simplePassword);
    }

    private String getAutogeneratedPassword() {
        return RandomStringUtils.randomAlphanumeric(PasswdUtil.DEFAULT_PASSWORD_LENGHT);
    }

    private byte[] getHash(String simplePassword) {
        return new PasswdUtil().hash(simplePassword);
    }

    public byte[] getHashedPassword() {
        return hashedPassword;
    }

    public String getSimplePassword() {
        return simplePassword;
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        builder.append("Password[")
                .append("simplePassword=")
                .append(simplePassword)
                .append(" hashedPassword=")
                .append(hashedPassword == null ? "null" : Arrays.toString(hashedPassword))
                .append(']');
        return builder.toString();
    }
}
